spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/catch_table
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 10000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
